apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
  name: logstash-02-types
  namespace: observability
data:
  values.yaml: |
    logstashPipeline:
      02-types.conf: |
        filter {
          if [type] == "firewall" {
            mutate {
              add_field => [ "[observer][type]", "firewall" ]
              ### Adjust the name, product and serial_number as desired ###
              add_field => [ "[observer][name]", "OPNsense" ]
              add_field => [ "[observer][product]", "Qotom" ]
              add_field => [ "[observer][serial_number]", "001" ]
            }
          }
          ### SURICATA ###
          if [type] == "suricata" {
            mutate {
              add_field => [ "[observer][type]", "suricata" ]
              ### Adjust the name, product and serial_number as desired ###
              add_field => [ "[observer][name]", "IDS" ]
              add_field => [ "[observer][product]", "Qotom" ]
              add_field => [ "[observer][serial_number]", "001" ]
            }
          }
          ### BEATS ###
          if [type] == "beats" {
            mutate {
              add_field => [ "[observer][type]", "beats" ]
            }
          }
        }
