apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
  name: logstash-05-firewall
  namespace: observability
data:
  values.yaml: |
    logstashPipeline:
      05-firewall.conf: |
        filter {
          if [process][name] =~ /^filterlog$/ {
            grok {
              patterns_dir => ["/usr/share/logstash/pipeline/patterns"]
              match => ["pfelk_message", "%{PF_LOG_ENTRY}"]
            }
            ### Change interface as desired ###
            if [interface][name] =~ /^igb0$/ {
              mutate {
                add_field => { "[interface][alias]" => "WAN" }
                add_field => { "[network][name]" => "FiOS" }
              }
            }
            ### Change interface as desired ###
            if [interface][name] =~ /^igb1$/ {
              mutate {
                add_field => { "[interface][alias]" => "LAN" }
                add_field => { "[network][name]" => "Home Network" }
              }
            }
            ### Change interface as desired ###
            if [interface][name] =~ /^igb1_vlan10$/ {
              mutate {
                add_field => { "[interface][alias]" => "IOT" }
                add_field => { "[network][name]" => "Internet of Shit" }
              }
            }
            ### Change interface as desired ###
            if [interface][name] =~ /^wg0$/ {
              mutate {
                add_field => { "[interface][alias]" => "WG0" }
                add_field => { "[network][name]" => "Wireguard" }
              }
            }
            ### Change interface as desired ###
            if [interface][name] =~ /^lo0$/ {
              mutate {
                add_field => { "[interface][alias]" => "Link-Local" }
                update => { "[network][direction]" => "%{[network][direction]}bound" }
                update => { "[network][type]" => "ipv%{[network][type]}" }
              }
            }
          }
        }
