apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
  name: logstash-35-rules-desc
  namespace: observability
data:
  values.yaml: |
    logstashPipeline:
      35-rules-desc.conf: |
        filter {
          if [observer][type] == "firewall" {
            if [rule][id] {
              translate {
                field => "[rule][id]"
                destination => "[rule][alias]"
                dictionary_path => "/usr/share/logstash/databases/rule-names.csv"
                refresh_interval => 60
                refresh_behaviour => replace
                fallback => "%{[rule][id]}"
              }
              mutate {
                add_field => { "[rule][description]" => "%{[interface][alias]}: %{[rule][alias]}" }
              }
            }
          }
        }
