apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
  name: logstash-50-outputs
  namespace: observability
data:
  values.yaml: |
    logstashPipeline:
      50-outputs.conf: |
        output {
          ### FIREWALL ###
          if "squid" not in [tags] and "unbound" not in [tags] and "suricata" not in [tags] and "snort" not in [tags] and "haproxy" not in [tags]{
            elasticsearch {
              id => "pfelk"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-firewall-%{+YYYY.MM.dd}"
              template_name => "pfelk-firewall"
            }
          }
          ### squid ###
          if [process][name] == "squid" {
            elasticsearch {
              id => "squid"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-squid-%{+YYYY.MM.dd}"
              template_name => "pfelk-squid"
            }
          }
          ### unbound ###
          if [process][name] == "unbound" {
            elasticsearch {
              id => "unbound"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-unbound-%{+YYYY.MM.dd}"
              template_name => "pfelk-unbound"
            }
          }
          ### suricata ###
          if [process][name] == "suricata" {
            elasticsearch {
              id => "suricata"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-suricata-%{+YYYY.MM.dd}"
              template_name => "pfelk-suricata"
              ### X-Pack Username and Password ###
              # user => USERNAMEHERE
              # password => PASSWORDHERE
            }
          }
          ### snort ###
          if [process][name] == "snort" {
            elasticsearch {
              id => "snort"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-snort-%{+YYYY.MM.dd}"
              template_name => "pfelk-snort"
              ### X-Pack Username and Password ###
              # user => USERNAMEHERE
              # password => PASSWORDHERE
            }
          }
          ### HAPROXY ###
          if [process][name] == "haproxy" {
            elasticsearch {
              id => "haproxy"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "pfelk-haproxy-%{+YYYY.MM.dd}"
              template_name => "pfelk-haproxy"
              ### X-Pack Username and Password ###
              # user => USERNAMEHERE
              # password => PASSWORDHERE
            }
          }
          ### BEATS ###
          if [type] == "beats" {
            elasticsearch {
              id => "beats"
              hosts => ["http://elasticsearch.brujordet.no:80"]
              #hosts => ["http://10.0.0.20:9200"]
              index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
              ### X-Pack Username and Password ###
              # user => USERNAMEHERE
              # password => PASSWORDHERE
            }
          }
        }

