---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: observability
spec:
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: 7.9.3
  interval: 1h0m0s
  releaseName: elasticsearch
  targetNamespace: observability
  values:
    clusterName: "elasticsearch"
    nodeGroup: "master"
    masterService: "elasticsearch-master"
    roles:
      master: "true"
      ingest: "true"
      data: "true"
    replicas: 3
    minimumMasterNodes: 2

    # Allows you to add any config files in /usr/share/elasticsearch/config/
    # such as elasticsearch.yml and log4j2.properties
    esConfig: {}
    #  elasticsearch.yml: |
    #    key:
    #      nestedkey: value
    #  log4j2.properties: |
    #    key = value

    esJavaOpts: "-Xmx1g -Xms1g"

    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    networkHost: "0.0.0.0"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - example.local

    # https://github.com/elastic/helm-charts/issues/63
    masterTerminationFix: false

    sysctlInitContainer:
      enabled: true
