apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash-udp
  namespace: observability
spec:
  ports:
  - name: firewall
    port: 5140
    protocol: UDP
    targetPort: 5140
  selector:
    app: logstash-logstash
    chart: logstash
    heritage: Helm
    release: logstash
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.8
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: logstash
    meta.helm.sh/release-namespace: observability
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash-tcp
  namespace: observability
spec:
  ports:
  - name: suricata
    port: 5141
    protocol: TCP
    targetPort: 5141
  selector:
    app: logstash-logstash
    chart: logstash
    heritage: Helm
    release: logstash
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.8
status:
  loadBalancer: {}
